/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.119
 * Generated at: 2026-07-11 19:59:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    // header.jsp - 公共导航栏（被 @include 包含，不要声明和主文件重复的变量！）
    // 假设主文件（如 index.jsp）已经声明了变量: ctx, 这里直接内联调用 request.getContextPath()
    Object userIdObj = session.getAttribute("userId");
    Object userRoleObj = session.getAttribute("userRole");
    Object nicknameObj = session.getAttribute("nickname");

    boolean loggedIn = userIdObj != null;
    String role = userRoleObj != null ? userRoleObj.toString() : "";
    String nickname = nicknameObj != null ? nicknameObj.toString() : "用户";
    String base = request.getContextPath();

      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print(base);
      out.write("/\">淘宝购物系统</a>\n");
      out.write("        <ul class=\"navbar-nav\">\n");
      out.write("            <li><a href=\"");
      out.print(base);
      out.write("/\">首页</a></li>\n");
      out.write("            <li><a href=\"");
      out.print(base);
      out.write("/product/list\">全部商品</a></li>\n");
      out.write("            ");
 if ("operator".equals(role)) { 
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/admin/stat/dashboard\">后台管理</a></li>\n");
      out.write("            ");
 } else if ("shopkeeper".equals(role)) { 
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/shop/home\">商家后台</a></li>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </ul>\n");
      out.write("        <form class=\"navbar-search\" action=\"");
      out.print(base);
      out.write("/product/search\" method=\"get\">\n");
      out.write("            <input type=\"text\" name=\"keyword\" placeholder=\"搜索商品...\" value=\"\">\n");
      out.write("            <button type=\"submit\">搜索</button>\n");
      out.write("        </form>\n");
      out.write("        <ul class=\"navbar-nav navbar-right\">\n");
      out.write("            ");
 if (!loggedIn) { 
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/login\">登录</a></li>\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/register\">注册</a></li>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                ");
 if ("customer".equals(role)) { 
      out.write("\n");
      out.write("                    <li><a href=\"");
      out.print(base);
      out.write("/cart/list\">🛒 购物车</a></li>\n");
      out.write("                    <li><a href=\"");
      out.print(base);
      out.write("/order/list\">📋 我的订单</a></li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <li class=\"dropdown\">\n");
      out.write("                    <a href=\"#\">👤 ");
      out.print(nickname);
      out.write(" ▾</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        ");
 if ("customer".equals(role)) { 
      out.write("\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/customer/profile\">个人中心</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/address/list\">收货地址</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/aftersale\">售后记录</a></li>\n");
      out.write("                        ");
 } else if ("shopkeeper".equals(role)) { 
      out.write("\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/shop/info/view\">店铺信息</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/shop/product/list\">商品管理</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/shop/order/list\">订单管理</a></li>\n");
      out.write("                        ");
 } else if ("operator".equals(role)) { 
      out.write("\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/stat/dashboard\">数据概览</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/user/list\">用户管理</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/shop/auditList\">店铺审核</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/order/list\">订单监控</a></li>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                        <li><a href=\"");
      out.print(base);
      out.write("/logout\">退出登录</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
