/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.119
 * Generated at: 2026-07-11 19:57:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.lang.reflect.Method;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    public String getProperty(Object obj, String propName) {
        if (obj == null) return "";
        if (obj instanceof java.util.Map) {
            java.util.Map map = (java.util.Map) obj;
            Object val = map.get(propName);
            return val == null ? "" : val.toString();
        }
        try {
            String getter = "get" + Character.toUpperCase(propName.charAt(0)) + propName.substring(1);
            Method m = obj.getClass().getMethod(getter);
            Object val = m.invoke(obj);
            return val == null ? "" : val.toString();
        } catch (Exception e1) {
            try {
                Method m = obj.getClass().getMethod("get_" + propName);
                Object val = m.invoke(obj);
                return val == null ? "" : val.toString();
            } catch (Exception e2) {
                return "";
            }
        }
    }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1783797844000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1783796460000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.lang.reflect.Method");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String ctx = request.getContextPath();
    Object userRole = session.getAttribute("userRole");
    Object userObj = session.getAttribute("user");
    boolean isCustomer = userObj != null && "customer".equals(userRole != null ? userRole.toString() : "");

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>淘宝购物系统 - 首页</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.bootcdn.net/ajax/libs/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(ctx);
      out.write("/css/style.css?v=4\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

    // header.jsp - 公共导航栏（被 @include 包含，不要声明和主文件重复的变量！）
    // 假设主文件（如 index.jsp）已经声明了变量: ctx, 这里直接内联调用 request.getContextPath()
    Object userIdObj = session.getAttribute("userId");
    Object userRoleObj = session.getAttribute("userRole");
    Object nicknameObj = session.getAttribute("nickname");

    boolean loggedIn = userIdObj != null;
    String role = userRoleObj != null ? userRoleObj.toString() : "";
    String nickname = nicknameObj != null ? nicknameObj.toString() : "用户";
    String base = request.getContextPath();

      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print(base);
      out.write("/\">淘宝购物系统</a>\n");
      out.write("        <ul class=\"navbar-nav\">\n");
      out.write("            <li><a href=\"");
      out.print(base);
      out.write("/\">首页</a></li>\n");
      out.write("            <li><a href=\"");
      out.print(base);
      out.write("/product/list\">全部商品</a></li>\n");
      out.write("            ");
 if ("operator".equals(role)) { 
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/admin/stat/dashboard\">后台管理</a></li>\n");
      out.write("            ");
 } else if ("shopkeeper".equals(role)) { 
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/shop/home\">商家后台</a></li>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </ul>\n");
      out.write("        <form class=\"navbar-search\" action=\"");
      out.print(base);
      out.write("/product/search\" method=\"get\">\n");
      out.write("            <input type=\"text\" name=\"keyword\" placeholder=\"搜索商品...\" value=\"\">\n");
      out.write("            <button type=\"submit\">搜索</button>\n");
      out.write("        </form>\n");
      out.write("        <ul class=\"navbar-nav navbar-right\">\n");
      out.write("            ");
 if (!loggedIn) { 
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/login\">登录</a></li>\n");
      out.write("                <li><a href=\"");
      out.print(base);
      out.write("/register\">注册</a></li>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                ");
 if ("customer".equals(role)) { 
      out.write("\n");
      out.write("                    <li><a href=\"");
      out.print(base);
      out.write("/cart/list\">🛒 购物车</a></li>\n");
      out.write("                    <li><a href=\"");
      out.print(base);
      out.write("/order/list\">📋 我的订单</a></li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <li class=\"dropdown\">\n");
      out.write("                    <a href=\"#\">👤 ");
      out.print(nickname);
      out.write(" ▾</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        ");
 if ("customer".equals(role)) { 
      out.write("\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/customer/profile\">个人中心</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/address/list\">收货地址</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/aftersale\">售后记录</a></li>\n");
      out.write("                        ");
 } else if ("shopkeeper".equals(role)) { 
      out.write("\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/shop/info/view\">店铺信息</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/shop/product/list\">商品管理</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/shop/order/list\">订单管理</a></li>\n");
      out.write("                        ");
 } else if ("operator".equals(role)) { 
      out.write("\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/stat/dashboard\">数据概览</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/user/list\">用户管理</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/shop/auditList\">店铺审核</a></li>\n");
      out.write("                            <li><a href=\"");
      out.print(base);
      out.write("/admin/order/list\">订单监控</a></li>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                        <li><a href=\"");
      out.print(base);
      out.write("/logout\">退出登录</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 公告栏 -->\r\n");
      out.write("    ");

        Object announcements = request.getAttribute("announcements");
        if (announcements instanceof List && !((List) announcements).isEmpty()) {
    
      out.write("\r\n");
      out.write("    <div class=\"announcement-bar\">\r\n");
      out.write("    ");

            List annList = (List) announcements;
            for (int i = 0; i < annList.size(); i++) {
                Object ann = annList.get(i);
                String id = getProperty(ann, "id");
                String title = getProperty(ann, "title");
    
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/announcement/detail?id=");
      out.print(id);
      out.write('"');
      out.write('>');
      out.print(title);
      out.write("</a>\r\n");
      out.write("    ");

            }
    
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 轮播图 -->\r\n");
      out.write("    <div class=\"carousel-section\">\r\n");
      out.write("        <div class=\"carousel-wrapper\">\r\n");
      out.write("            <div class=\"carousel\">\r\n");
      out.write("                <div class=\"carousel-inner\">\r\n");
      out.write("                    <div class=\"slide active\">\r\n");
      out.write("                        <img src=\"https://picsum.photos/1200/400?random=1\" alt=\"Banner1\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <h3>欢迎来到淘宝购物系统</h3>\r\n");
      out.write("                            <p>海量精选商品，品质保证，无忧购物</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"slide\">\r\n");
      out.write("                        <img src=\"https://picsum.photos/1200/400?random=2\" alt=\"Banner2\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <h3>限时特惠 惊喜不断</h3>\r\n");
      out.write("                            <p>每日精选爆款，超低价格等你来抢</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"slide\">\r\n");
      out.write("                        <img src=\"https://picsum.photos/1200/400?random=3\" alt=\"Banner3\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <h3>新品首发 抢先体验</h3>\r\n");
      out.write("                            <p>潮流新品第一时间上架，引领时尚前沿</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"slide\">\r\n");
      out.write("                        <img src=\"https://picsum.photos/1200/400?random=4\" alt=\"Banner4\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <h3>品质保障 放心购物</h3>\r\n");
      out.write("                            <p>正品保证，七天无理由退换，售后无忧</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"slide\">\r\n");
      out.write("                        <img src=\"https://picsum.photos/1200/400?random=5\" alt=\"Banner5\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <h3>会员专享 超值福利</h3>\r\n");
      out.write("                            <p>注册即送优惠券，积分兑换好礼不停</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"carousel-btn prev\" onclick=\"carouselPrev()\">&lsaquo;</button>\r\n");
      out.write("                <button class=\"carousel-btn next\" onclick=\"carouselNext()\">&rsaquo;</button>\r\n");
      out.write("                <div class=\"carousel-dots\">\r\n");
      out.write("                    <span class=\"dot active\" onclick=\"goToSlideDot(0)\"></span>\r\n");
      out.write("                    <span class=\"dot\" onclick=\"goToSlideDot(1)\"></span>\r\n");
      out.write("                    <span class=\"dot\" onclick=\"goToSlideDot(2)\"></span>\r\n");
      out.write("                    <span class=\"dot\" onclick=\"goToSlideDot(3)\"></span>\r\n");
      out.write("                    <span class=\"dot\" onclick=\"goToSlideDot(4)\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 分类导航 -->\r\n");
      out.write("    <div class=\"page-container category-section\">\r\n");
      out.write("        <div class=\"category-nav\">\r\n");
      out.write("            <h4>商品分类</h4>\r\n");
      out.write("            <a href=\"javascript:void(0)\" onclick=\"loadProducts('')\" class=\"");
      out.print(request.getAttribute("selectedCategory") == null ? "active" : "");
      out.write("\">全部</a>\r\n");
      out.write("            ");

                Object categories = request.getAttribute("categories");
                if (categories instanceof List) {
                    List catList = (List) categories;
                    String selectedCategory = (String) request.getAttribute("selectedCategory");
                    for (int i = 0; i < catList.size(); i++) {
                        Object cat = catList.get(i);
                        String name = getProperty(cat, "name");
                        boolean isActive = selectedCategory != null && selectedCategory.equals(name);
            
      out.write("\r\n");
      out.write("            <a href=\"javascript:void(0)\" onclick=\"loadProducts('");
      out.print(name);
      out.write("')\" class=\"");
      out.print(isActive ? "active" : "");
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\r\n");
      out.write("            ");

                    }
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 商品列表 -->\r\n");
      out.write("    <div class=\"page-container product-section\">\r\n");
      out.write("        <div class=\"section-header\">\r\n");
      out.write("            <h2>\r\n");
      out.write("                ");

                    String selectedCategory = (String) request.getAttribute("selectedCategory");
                    if (selectedCategory != null && !selectedCategory.isEmpty()) {
                        out.print(selectedCategory);
                    } else {
                        out.print("全部商品");
                    }
                
      out.write("\r\n");
      out.write("            </h2>\r\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/product/list\">查看全部 →</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-grid\">\r\n");
      out.write("            ");

                Object products = request.getAttribute("products");
                if (products instanceof List) {
                    List prodList = (List) products;
                    if (prodList.isEmpty()) {
            
      out.write("\r\n");
      out.write("            <div style=\"text-align: center; padding: 40px; color: #999;\">暂无商品</div>\r\n");
      out.write("            ");

                    } else {
                        for (int i = 0; i < prodList.size(); i++) {
                            Object prod = prodList.get(i);
                            String id = getProperty(prod, "id");
                            String name = getProperty(prod, "name");
                            String image = getProperty(prod, "main_image");
                            if (image.equals("")) image = getProperty(prod, "mainImage");
                            if (image.equals("") || image.startsWith("/upload/")) {
                                image = "https://picsum.photos/300/300?random=" + id;
                            }
                            String price = getProperty(prod, "price");
                            String originalPrice = getProperty(prod, "originalPrice");
            
      out.write("\r\n");
      out.write("            <div class=\"product-card\">\r\n");
      out.write("                <div class=\"product-image\">\r\n");
      out.write("                    <a href=\"");
      out.print(ctx);
      out.write("/product/detail?id=");
      out.print(id);
      out.write("\">\r\n");
      out.write("                        <img src=\"");
      out.print(image);
      out.write("\" alt=\"");
      out.print(name);
      out.write("\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-info\">\r\n");
      out.write("                    <div class=\"product-name\"><a href=\"");
      out.print(ctx);
      out.write("/product/detail?id=");
      out.print(id);
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a></div>\r\n");
      out.write("                    <div class=\"product-desc\">精选品质，限时特惠</div>\r\n");
      out.write("                    <div class=\"product-price-row\">\r\n");
      out.write("                        <div class=\"product-price\">\r\n");
      out.write("                            ￥");
      out.print(price);
      out.write("\r\n");
      out.write("                            ");
 if (originalPrice != null && !originalPrice.equals("") && !originalPrice.equals(price)) { 
      out.write("\r\n");
      out.write("                                <small>￥");
      out.print(originalPrice);
      out.write("</small>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 if (isCustomer) { 
      out.write("\r\n");
      out.write("                            <a href=\"");
      out.print(ctx);
      out.write("/cart/add?productId=");
      out.print(id);
      out.write("\" class=\"add-cart-btn\">加入购物车</a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                        }
                    }
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\n");
      out.write("<!-- 底部公共页面 -->\n");
      out.write("<footer class=\"app-footer\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"footer-row\">\n");
      out.write("      <div>\n");
      out.write("        <h4>淘宝购物系统</h4>\n");
      out.write("        <p>JSP+Servlet电商平台演示项目</p>\n");
      out.write("      </div>\n");
      out.write("      <div>\n");
      out.write("        <h4>快速链接</h4>\n");
      out.write("        <ul>\n");
      out.write("          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">首页</a></li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/list\"\n");
      out.write("              >商品列表</a\n");
      out.write("            >\n");
      out.write("          </li>\n");
      out.write("          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">登录</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <div>\n");
      out.write("        <h4>联系我们</h4>\n");
      out.write("        <p>客服邮箱: support@taobao-shop.com</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <hr />\n");
      out.write("    <p class=\"text-center\">&copy; 2026 淘宝购物系统 - 期末考查项目</p>\n");
      out.write("  </div>\n");
      out.write("</footer>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.bootcdn.net/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.bootcdn.net/ajax/libs/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        var carouselIndex = 0;\r\n");
      out.write("        var carouselSlides = document.querySelectorAll('.carousel-inner .slide');\r\n");
      out.write("        var carouselDots = document.querySelectorAll('.carousel-dots .dot');\r\n");
      out.write("        var autoPlayTimer = null;\r\n");
      out.write("        \r\n");
      out.write("        function updateDots() {\r\n");
      out.write("            carouselDots.forEach(function(dot, index) {\r\n");
      out.write("                dot.classList.toggle('active', index === carouselIndex);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function goToSlide(index, direction) {\r\n");
      out.write("            if (index === carouselIndex) return;\r\n");
      out.write("            \r\n");
      out.write("            var currentSlide = carouselSlides[carouselIndex];\r\n");
      out.write("            var targetSlide = carouselSlides[index];\r\n");
      out.write("            \r\n");
      out.write("            currentSlide.classList.remove('prev', 'next');\r\n");
      out.write("            targetSlide.classList.remove('prev', 'next');\r\n");
      out.write("            currentSlide.classList.add('active');\r\n");
      out.write("            \r\n");
      out.write("            if (direction === 'next') {\r\n");
      out.write("                targetSlide.style.transform = 'translateX(100%)';\r\n");
      out.write("                targetSlide.style.opacity = '0';\r\n");
      out.write("                targetSlide.style.transition = 'none';\r\n");
      out.write("                \r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    targetSlide.style.transition = '';\r\n");
      out.write("                    currentSlide.classList.remove('active');\r\n");
      out.write("                    currentSlide.classList.add('prev');\r\n");
      out.write("                    targetSlide.classList.add('active');\r\n");
      out.write("                    targetSlide.style.transform = '';\r\n");
      out.write("                    targetSlide.style.opacity = '';\r\n");
      out.write("                }, 20);\r\n");
      out.write("            } else {\r\n");
      out.write("                targetSlide.style.transform = 'translateX(-100%)';\r\n");
      out.write("                targetSlide.style.opacity = '0';\r\n");
      out.write("                targetSlide.style.transition = 'none';\r\n");
      out.write("                \r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    targetSlide.style.transition = '';\r\n");
      out.write("                    currentSlide.classList.remove('active');\r\n");
      out.write("                    currentSlide.classList.add('next');\r\n");
      out.write("                    targetSlide.classList.add('active');\r\n");
      out.write("                    targetSlide.style.transform = '';\r\n");
      out.write("                    targetSlide.style.opacity = '';\r\n");
      out.write("                }, 20);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("                currentSlide.classList.remove('active', 'prev', 'next');\r\n");
      out.write("            }, 520);\r\n");
      out.write("            \r\n");
      out.write("            carouselIndex = index;\r\n");
      out.write("            updateDots();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function goToSlideDot(index) {\r\n");
      out.write("            if (index === carouselIndex) return;\r\n");
      out.write("            var direction = index > carouselIndex ? 'next' : 'prev';\r\n");
      out.write("            goToSlide(index, direction);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function carouselNext() {\r\n");
      out.write("            var nextIndex = (carouselIndex + 1) % carouselSlides.length;\r\n");
      out.write("            goToSlide(nextIndex, 'next');\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function carouselPrev() {\r\n");
      out.write("            var prevIndex = (carouselIndex - 1 + carouselSlides.length) % carouselSlides.length;\r\n");
      out.write("            goToSlide(prevIndex, 'prev');\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function startAutoPlay() {\r\n");
      out.write("            autoPlayTimer = setInterval(carouselNext, 5000);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function stopAutoPlay() {\r\n");
      out.write("            if (autoPlayTimer) {\r\n");
      out.write("                clearInterval(autoPlayTimer);\r\n");
      out.write("                autoPlayTimer = null;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        var carouselEl = document.querySelector('.carousel');\r\n");
      out.write("        if (carouselEl) {\r\n");
      out.write("            carouselEl.addEventListener('mouseenter', stopAutoPlay);\r\n");
      out.write("            carouselEl.addEventListener('mouseleave', startAutoPlay);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        startAutoPlay();\r\n");
      out.write("        \r\n");
      out.write("        function loadProducts(category) {\r\n");
      out.write("            $('.category-nav a').removeClass('active');\r\n");
      out.write("            if (category === '') {\r\n");
      out.write("                $('.category-nav a:first').addClass('active');\r\n");
      out.write("            } else {\r\n");
      out.write("                $('.category-nav a:contains(\"' + category + '\")').addClass('active');\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            var title = category === '' ? '全部商品' : category;\r\n");
      out.write("            $('.section-header h2').text(title);\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: '");
      out.print(ctx);
      out.write("/product/ajax',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                data: { category: category },\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                success: function(products) {\r\n");
      out.write("                    var html = '';\r\n");
      out.write("                    if (products.length === 0) {\r\n");
      out.write("                        html = '<div style=\"text-align: center; padding: 40px; color: #999;\">暂无商品</div>';\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $.each(products, function(index, p) {\r\n");
      out.write("                            var image = p.main_image && p.main_image !== '' && !p.main_image.startsWith('/upload/') \r\n");
      out.write("                                ? p.main_image : 'https://picsum.photos/300/300?random=' + p.id;\r\n");
      out.write("                            html += '<div class=\"product-card\">' +\r\n");
      out.write("                                '<div class=\"product-image\">' +\r\n");
      out.write("                                '<a href=\"");
      out.print(ctx);
      out.write("/product/detail?id=' + p.id + '\">' +\r\n");
      out.write("                                '<img src=\"' + image + '\" alt=\"' + p.name + '\">' +\r\n");
      out.write("                                '</a></div>' +\r\n");
      out.write("                                '<div class=\"product-info\">' +\r\n");
      out.write("                                '<div class=\"product-name\"><a href=\"");
      out.print(ctx);
      out.write("/product/detail?id=' + p.id + '\">' + p.name + '</a></div>' +\r\n");
      out.write("                                '<div class=\"product-desc\">精选品质，限时特惠</div>' +\r\n");
      out.write("                                '<div class=\"product-price-row\">' +\r\n");
      out.write("                                '<div class=\"product-price\">￥' + p.price + '</div>' +\r\n");
      out.write("                                '</div></div></div>';\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                    $('.product-grid').html(html);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
